# This is a basic workflow to help you get started with Actions

name: Python Greetings workflow
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'dev'
  api-tests-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Step
        run: echo "Api tests on DEV"
  deploy-stg:
    runs-on: ubuntu-latest
    needs: [api-tests-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'stg'
  api-tests-stg:
    runs-on: ubuntu-latest
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Step
        run: echo "Api tests on STG"
  deploy-prd:
    runs-on: ubuntu-latest
    needs: [api-tests-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'prd'
  api-tests-dev:
    runs-on: ubuntu-latest
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Step
        run: echo "Api tests on PRD"